esphome:
  name: esp32-master-test

esp32:
  board: az-delivery-devkit-v4
  framework:
    type: arduino

# Enable logging
logger:

web_server:
  port: 80
# Enable Home Assistant API
api:
  password: ""

ota:
  - platform: esphome
    password: ""

wifi:
  networks:
    - ssid: "Mb-ht"
      password: "zerowanie"
    - ssid: "komandor_shepard"
      password: "uziemienie poprzez zerowanie"
    - ssid: "ANS"
      password: "orw-els-2000!?"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32-Master-Test"
    password: "3wlz0W77fMh5"

captive_portal:
    
external_components:
  - source: 
      type: local
      path: custom_components


  # - id: itron_uart
  #   tx_pin: GPIO33
  #   rx_pin: GPIO32
  #   baud_rate: 300
  #   data_bits: 7
  #   parity: EVEN
  #   stop_bits: 1
  #   #debug:
  #   #  direction: BOTH
  #   #  dummy_receiver: true



#DI1: GPIO14
#DO1: GPIO12
#RE1: GPIO13 //Output HIGH, Input LOW

#DI2: GPIO27
#DO2: GPIO25
#RE2: GPIO26

uart:
  id: uart_bus
  tx_pin: 14        # DI1
  rx_pin: 16        # DO1
  baud_rate: 4800
  data_bits: 7
  parity: EVEN
  stop_bits: 1

pozyton_energy_meters:
  id: my_meter
  meter_type: EABM
  dir_pin: GPIO13
  update_interval: 10s
  debug: true

sensor:
  - platform: pozyton_energy_meters
    pozyton_id: my_meter
    obis: "1.8.0"
    name: "Positive Active Energy"
